### ISSUE TITLE
senza wait broken  broken in senza 1.0.72

### ISSUE THREAD

**Issue by kenden** [zalando-stups/senza#243]
Senza was working in version 1.0.69, but seems to be broken in the last version (1.0.72).
It fails with: "missing 1 required positional argument: 'stacktrace_visible'"

@jmcs 
```
$ senza wait --stacktrace-visible --region eu-central-1 senza-template.yml stack
Traceback (most recent call last):
  File "/Users/user/project/.venv/bin/senza", line 11, in <module>
    sys.exit(main())
  File "/Users/user/project/.venv/lib/python3.5/site-packages/senza/cli.py", line 1454, in main
    HandleExceptions(cli)()
  File "/Users/user/project/.venv/lib/python3.5/site-packages/senza/error_handling.py", line 39, in __call__
    self.function(*args, **kwargs)
  File "/Users/user/project/.venv/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/project/.venv/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/user/project/.venv/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/user/project/.venv/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user/project/.venv/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
TypeError: wait() missing 1 required positional argument: 'stacktrace_visible'

$ senza wait --region eu-central-1 senza-template.yml stack
Unknown Error: wait() missing 1 required positional argument: 'stacktrace_visible'.
Please create an issue with the content of /var/folders/90/pz80sxl93gl11zjsbmylwmxj42vx03/T/senza-traceback-vqlk198g

$ cat /var/folders/90/pz80sxl93gl11zjsbmylwmxj42vx03/T/senza-traceback-vqlk198g
Traceback (most recent call last):
  File "/Users/user/project/.venv/lib/python3.5/site-packages/senza/error_handling.py", line 39, in __call__
    self.function(*args, **kwargs)
  File "/Users/user/project/.venv/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/project/.venv/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/user/project/.venv/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/user/project/.venv/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user/project/.venv/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
TypeError: wait() missing 1 required positional argument: 'stacktrace_visible'
```
