### ISSUE TITLE
Senza stack creation broken with latest Pier One CLI upgrade

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/senza#229]
Cannot create a stack after senza version upgrade:

```
File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pierone/api.py", line 102, in image_exists
url = 'https://{}'.format(image.registry)
AttributeError: 'str' object has no attribute 'registry'

**Comment by hjacobs** [comment]
This was caused by https://github.com/zalando-stups/pierone-cli/pull/38

**Comment by hjacobs** [comment]
This will probably be fixed with #226, but maybe we need to provide a quick fix earlier (?)

**Comment by rafaelcaricio** [comment]
@hjacobs basically the fix is https://github.com/zalando-stups/senza/pull/226/files

**Comment by hjacobs** [comment]
@rafaelcaricio ok, next time we should make sure (including myself during review) that we don't simply change functions in the "api" module as they are "exposed" to other tools.

**Comment by hjacobs** [comment]
Fixed with the latest release: https://github.com/zalando-stups/senza/releases/tag/1.0.65

**Comment by rafaelcaricio** [comment]
@hjacobs I think we should use the commands as subprocess instead of calling directly the source code to avoid this kind of things. It blocks one code of evolving because of misterious "clients" using the code as public interface. Besides that this dependency is only in our heads which means we have to remember that they exist.

**Comment by hjacobs** [comment]
@rafaelcaricio that's why I called it "api" module, so it was the whole idea to have an API library.

**Comment by rafaelcaricio** [comment]
How would be a better way to update the signature of the functions existing in the `api` module?
